apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  name: tumbleweed-minimal
  namespace: harvester-public
spec:
  displayName: Tumbleweed-Minimal-Cloud
  sourceType: download
  url: https://download.opensuse.org/tumbleweed/appliances/openSUSE-Tumbleweed-Minimal-VM.x86_64-Cloud.qcow2
