apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ref-tumbleweed-01
  namespace: default
  annotations:
    harvesterhci.io/sshNames: '["default/mhahl-sk-ecdsa", "default/mhahl-sk-ed25519"]'
    harvesterhci.io/volumeClaimTemplates: |-
      [{
        "metadata": {
          "name": "pvc-ref-tumbleweed-01",
          "annotations": {
            "harvesterhci.io/imageId": "harvester-public/tumbleweed-minimal"
          }
        },
        "spec":{
          "storageClassName": "lh-93d34ccb-7e92-4014-b5dc-5a9fdb6fb1e0",
          "accessModes": ["ReadWriteMany"],
          "resources":{
            "requests":{
              "storage": "20Gi"
            }
          },
          "volumeMode": "Block"
        }
      }]
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        harvesterhci.io/vmName: ref-tumbleweed-01
    spec:
      domain:
        machine:
          type: q35
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        memory:
          guest: 4Gi
        features:
          acpi:
            enabled: true
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            model: virtio
            name: nic-1
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
      evictionStrategy: LiveMigrateIfPossible
      hostname: ref-tumbleweed-01
      networks:
      - multus:
          networkName: vlan14-server
        name: nic-1
      volumes:
      - name: rootdisk
        persistentVolumeClaim:
          claimName: pvc-ref-tumbleweed-01
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: ref-tumbleweed-01
            ssh_pwauth: false
            users:
              - name: mhahl
                sudo: ALL=(ALL) NOPASSWD:ALL
                ssh_authorized_keys:
                  - sk-ecdsa-sha2-nistp256@openssh.com AAAAInNrLWVjZHNhLXNoYTItbmlzdHAyNTZAb3BlbnNzaC5jb20AAAAIbmlzdHAyNTYAAABBBFbNXF81/IgFb74l2uptFfRNJaKvRZ5TKtpX/W+wqtc7tXzCLHzTxQJBhZIoqhnSIg8arC8w6exHmCrwkZetQGkAAAAEc3NoOg== Mark Hahl <mark.hahl@sigaint.au>
                  - sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIOegI4lEpCI30T4DgzJEk3W1NF+VhhoBeaoA23w51bQxAAAABHNzaDo= Mark Hahl Token2 <mark.hahl@sigaint.au>
          networkData: |
            version: 1
            config:
              - type: physical
                name: eth0
                match:
                  driver: virtio_net
                subnets:
                  - type: dhcp
        name: cloudinitdisk
