# Tell Harvester which snapshot class backs VM snapshots and backups for
# the Longhorn provisioner.
apiVersion: harvesterhci.io/v1beta1
kind: Setting
metadata:
  name: csi-driver-config
value: '{"driver.longhorn.io":{"volumeSnapshotClassName":"longhorn-snapshot","backupVolumeSnapshotClassName":"longhorn"}}'
